# Generated by Django 5.1.6 on 2025-03-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(default='noname', max_length=50),
            preserve_default=False,
        ),
    ]
