# Generated by Django 5.1.6 on 2025-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_fio'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='tags',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
