# Generated by Django 5.1.6 on 2025-03-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_mentorprofile_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='tg',
            field=models.CharField(default='nousername', max_length=256, unique=True, verbose_name='TG username'),
            preserve_default=False,
        ),
    ]
