# Generated by Django 5.1.6 on 2025-03-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_user_email_user_tg'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
    ]
