# Generated by Django 5.1.6 on 2025-03-02 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=1024, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Принято'), ('in_process', 'В процессе'), ('declined', 'Отклонено')], max_length=20)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ment', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='tags.tag')),
            ],
        ),
    ]
